# SPDX-FileCopyrightText: 2026 Roy Kollen Svendsen
#
# SPDX-License-Identifier: GPL-3.0-or-later
"""Generate the app's composed-hold data from the measured JSON models.

Usage: ``python gen_dart.py > ../../lib/features/felt/presentation/felt_hold_art_data.dart``

Reads ``models/hold-{1..8}.json`` (produced by the reconstruction harness) and
emits ``const List<FeltHoldArt> norgesfelt2026Art`` — the same shape the traced
``felt_figure_paths.dart`` is generated in. Only reconstructed vector data is
emitted; no source images are involved.
"""
from __future__ import annotations

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))


def col(rgb):
    r, g, b = (int(round(v)) for v in rgb)
    return f'Color(0x{0xFF:02X}{r:02X}{g:02X}{b:02X})'


def num(v):
    return str(int(v)) if float(v).is_integer() else f'{float(v):.1f}'


def ring_arg(f):
    inner = f.get('inner')
    if not inner:
        return ''  # ring defaults to null; omit to avoid a redundant argument
    return (f", ring: FeltArtRing(cx: {num(inner['cx'])}, "
            f"cy: {num(inner['cy'])}, r: {num(inner['r'])}, "
            f"strokeWidth: {num(inner.get('strokeW', 1.5))}, "
            f"color: {col(inner['color'])})")


def figure(f):
    p = f['params']
    fill = col(f['fill'])
    r = ring_arg(f)
    t = f['type']
    if t == 'circle':
        return (f"FeltArtFigure(shape: FeltArtShape.circle, cx: {num(p['cx'])}, "
                f"cy: {num(p['cy'])}, r: {num(p['r'])}, fill: {fill}{r})")
    if t == 'tcircle':
        return (f"FeltArtFigure(shape: FeltArtShape.tcircle, cx: {num(p['cx'])},"
                f" cy: {num(p['cy'])}, r: {num(p['r'])}, "
                f"bottomY: {num(p['bottomY'])}, fill: {fill}{r})")
    if t == 'ellipse':
        return (f"FeltArtFigure(shape: FeltArtShape.ellipse, cx: {num(p['cx'])},"
                f" cy: {num(p['cy'])}, a: {num(p['a'])}, b: {num(p['b'])}, "
                f"thetaDeg: {num(p['theta'])}, fill: {fill}{r})")
    pts = ', '.join(f'Offset({num(x)}, {num(y)})' for x, y in p['points'])
    return (f"FeltArtFigure(shape: FeltArtShape.polygon, "
            f"points: <Offset>[{pts}], fill: {fill}{r})")


def plate(pl):
    x, y, w, h = pl['rect']
    return (f"FeltArtPlate(rect: Rect.fromLTWH({num(x)}, {num(y)}, {num(w)}, "
            f"{num(h)}), color: {col(pl['color'])}, "
            f"radius: {num(pl.get('radius', 0))})")


def separator(sp):
    x, y, w, h = sp['rect']
    c = col(sp.get('color', [16, 16, 16]))
    return (f"FeltArtSeparator(rect: Rect.fromLTWH({num(x)}, {num(y)}, "
            f"{num(w)}, {num(h)}), color: {c})")


def hold(m):
    w, h = m['size']
    plates = ', '.join(plate(p) for p in m.get('plates', []))
    figs = ', '.join(figure(f) for f in m.get('figures', []))
    seps = ', '.join(separator(s) for s in m.get('separators', []))
    return (
        f"  FeltHoldArt(\n"
        f"    number: {m['hold']},\n"
        f"    size: Size({num(w)}, {num(h)}),\n"
        f"    paper: {col(m.get('paper', [255, 255, 255]))},\n"
        f"    plates: <FeltArtPlate>[{plates}],\n"
        f"    figures: <FeltArtFigure>[{figs}],\n"
        f"    separators: <FeltArtSeparator>[{seps}],\n"
        f"  ),"
    )


def main():
    holds = []
    for n in range(1, 9):
        with open(os.path.join(HERE, 'models', f'hold-{n}.json')) as fh:
            holds.append(json.load(fh))
    body = '\n'.join(hold(m) for m in holds)
    print(f"""// SPDX-FileCopyrightText: 2026 Roy Kollen Svendsen
//
// SPDX-License-Identifier: GPL-3.0-or-later

// Composed NorgesFelt 2026 holds (spec 0079), generated by tool/felt/gen_dart.py
// from the measured reconstruction models (tool/felt/models/hold-N.json).
// Reconstructed vector data; run `dart format` after regenerating.
import 'dart:ui';

import 'package:treffpunkt/features/felt/presentation/felt_hold_art.dart';

/// The eight composed holds of the NorgesFelt 2026 course.
const List<FeltHoldArt> norgesfelt2026Art = <FeltHoldArt>[
{body}
];""")


if __name__ == '__main__':
    main()
